name: news_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  auto_route: ^7.8.4
  bloc: ^8.1.3
  cached_network_image: ^3.3.1
  dartz: ^0.10.1
  dio: ^5.4.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  get_it: ^7.6.7
  hive: ^2.2.3
  injectable: ^2.3.2
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  slang: ^3.29.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  injectable_generator: ^2.4.1
  build_runner: ^2.4.8
  auto_route_generator: ^7.3.2
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true